---
title: "02_research_design"
description: |
    Support notebook to compute basic stats related to the materials and methods used in the study, which is connected to section 2 (*Research design*). 

#execute:
#  echo: false
format: 
  html:
    toc: true
    embed-resources: true  # Self-contained
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
---


```{r}
#| label: load-packages
#| message: false

library(here)
library(tidyverse)
library(dplyr)
library(scales)
library(stringr)
library(gt)
library(ggplot2)
```


```{r}
#| label: load-data
#| message: false

papers <- 
  readr::read_csv(here::here("data-clean", "all-data.csv"))

papers <- 
  papers |>
  dplyr::select(conf, paper, year) |>
  dplyr::arrange(conf, year)


```


Selected/relevant columns are: `{r} stringr::str_flatten_comma(names(papers))`. More details [here](https://github.com/nuest/reproducible-research-giscience-longitudinal-study/tree/main/data-clean).


```{r}
#| label: basic-counts
#| message: false

n_papers <- nrow(papers)
n_papers_agile <- 
  papers |>
  count(conf) |>
  filter(conf == "agile") |>
  pull(n)

n_papers_giscience <- 
  papers |>
  count(conf) |>
  filter(conf == "giscience") |>
  pull(n)
```


```{r}
#| label: tbl-papers
#| tbl-cap: "Distribution of conference papers"

papers |>
  dplyr::group_by(conf) |>
  dplyr::count(year) |>
  dplyr::arrange(year, desc(n)) |>
  gt::gt() |>
  gt::tab_header(
    title = stringr::str_glue("Distribution of conference papers (N={n_papers})"),
    subtitle = md("(Section 2.1 *Data collection process and corpus*)")
  ) |>
  gt::summary_rows(
    groups = everything(),
    columns = n,
    fns = list(
      total = "sum"
    )
  ) |> 
  gt::cols_label(
    year = md("**Year**"),
    n = md("**#**"),
  )

```


```{r}
#| label: tbl-batches
#| message: false


papers |>
  dplyr::mutate(
    batch = 
      dplyr::case_when(
        (conf == "agile" & year == 2019) ~ 1,
        (conf == "agile" & year == 2021)  ~ 1,
        (conf == "giscience" & year == 2020) ~ 1,
        (conf == "giscience" & year == 2021)  ~ 1,
        (conf == "agile" & year == 2018) ~ 2,
        (conf == "agile" & year == 2022)  ~ 2,
        (conf == "giscience" & year == 2018) ~ 2,
        (conf == "agile" & year == 2017) ~ 3,
        (conf == "agile" & year == 2023)  ~ 3,
        (conf == "giscience" & year == 2023) ~ 3,
        (conf == "agile" & year == 2020) ~ 4,
        (conf == "agile" & year == 2024)  ~ 4,
        (conf == "giscience" & year == 2016) ~ 4,
        TRUE ~ 0)
    ) |>
  dplyr::count(batch) |>
  gt::gt() |>
  gt::tab_header(
    title = stringr::str_glue("Distribution of conference papers in batches (N={n_papers})"),
    subtitle = md("(Section 2.2 *Assessing potential reproducibility*)")
  ) |>
  gt::cols_label(
    batch = md("**Batch**"),
    n = md("**#**"),
  )
```
